// ── Data Schemas for Template-Based Artifact Generation ──────────────────────
// Claude generates these JSON data objects; the template shells render them.

// ── Build Plan (Cornerstone Skillset Manual format) ──────────────────────────

export interface BuildPlanAccount {
  name: string;
  setup: string;
  connection: string;
  icon: string;
  color: string;
}

export interface BuildPlanSpFolder {
  content: string;
  find: string;
  variable: string;
  color: string;
}

export interface BuildPlanTrainingRow {
  num: number;
  name: string;
  type: string;
  tools: string;
  trigger: string;
  inputs: string;
  outputs: string;
  typeColor: string;
}

export interface BuildPlanScenarioTemplate {
  name: string;
  purpose: string;
  mergeTags: string[];
}

export interface BuildPlanScenario {
  id: string;
  name: string;
  trigger: string;
  purpose: string;
  icon: string;
  modules: number;
  type: string;
  claude: boolean;
  details: string;
  frMap: string[];
  moduleList: string[];
  template: BuildPlanScenarioTemplate | null;
}

export interface BuildPlanSystemPromptRule {
  num: number;
  title: string;
  desc: string;
  color: string;
}

export interface BuildPlanJsonSchema {
  name: string;
  fields: number;
  used: string;
  desc: string;
  arrays: string[];
}

export interface BuildPlanMakeVar {
  name: string;
  purpose: string;
  example: string;
}

export interface BuildPlanConditionalLogic {
  scenario: string;
  condition: string;
  action: string;
  elseAction: string;
  color: string;
}

export interface BuildPlanErrorHandling {
  trigger: string;
  response: string;
  severity: string;
}

export interface BuildPlanBPItem {
  label: string;
  detail: string;
  type: string;
}

export interface BuildPlanBPCategory {
  category: string;
  icon: string;
  color: string;
  items: BuildPlanBPItem[];
}

export interface BuildPlanData {
  clientName: string;
  solutionName: string;
  version: string;
  stack: string;
  confidentialLine: string;
  calloutTitle: string;
  calloutBody: string;
  scopeIn: string[];
  scopeOut: string[];
  accounts: BuildPlanAccount[];
  spFolders: BuildPlanSpFolder[];
  trainingRows: BuildPlanTrainingRow[];
  scenarios: BuildPlanScenario[];
  systemPromptRules: BuildPlanSystemPromptRule[];
  jsonSchemas: BuildPlanJsonSchema[];
  makeVars: BuildPlanMakeVar[];
  conditionalLogic: BuildPlanConditionalLogic[];
  errorHandling: BuildPlanErrorHandling[];
  guardrails: string[];
  operationalBP: BuildPlanBPCategory[];
  buildBP: BuildPlanBPCategory[];
  // systemPromptText is NOT generated by Claude — too large.
  // The template provides a default system prompt placeholder.
}

// ── Solution Demo (Sunstate Solution Demo format) ────────────────────────────

export interface SolutionDemoTripData {
  date: string;
  time: string;
  patient: string;
  patPhone: string;
  patEmail: string;
  facility: string;
  facPhone: string;
  pickup: string;
  dest: string;
  type: string;
  caStatus: string;
  notes: string;
  callResult: string;
  callNotes: string;
  callTs: string;
}

export interface SolutionDemoTranscriptLine {
  speaker: string;
  text: string;
  delay: number;
}

export interface SolutionDemoScenario {
  id: string;
  name: string;
  color: string;
  trust: string;
  build: string;
  trigger: string;
  scId: string;
  desc: string;
  modules: string[];
}

export interface SolutionDemoTechStack {
  icon: string;
  name: string;
  role: string;
  color: string;
}

export interface SolutionDemoData {
  clientName: string;
  solutionName: string;
  version: string;
  stack: string;
  confidentialLine: string;
  overviewTitle: string;
  overviewDesc: string;
  calloutTitle: string;
  calloutBody: string;
  statsScenarios: string;
  statsTools: string;
  statsGptStages: string;
  retellAgentId: string;
  retellFromNumber: string;
  retellVoiceEngine: string;
  retellDashUrl: string;
  sheetId: string;
  sheetRange: string;
  manifestTitle: string;
  manifestDate: string;
  tripData: SolutionDemoTripData[];
  transcriptLines: SolutionDemoTranscriptLine[];
  scenarios: SolutionDemoScenario[];
  techStack: SolutionDemoTechStack[];
}
